version: '3.7'

services:
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db

  item-app:
    image: rrafids/item-app:v1
    ports:
      - 80:8080
    depends_on:
      - item-db
      
volumes:
  app-db: